version: '3.8'

services:
  shortener-frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: shortener-frontend
    ports:
      - "80:8080"
    restart: unless-stopped
    networks:
      - shortener-network

networks:
  shortener-network:
    driver: bridge
    name: shortener-network
